### ISSUE TITLE
Can you include a build?

### ISSUE THREAD

**Issue by aarongustafson** [webrender/10ktower#2]
It would make things easier for us to just run the install and start the server.

**Comment by webrender** [comment]
Sure.  Question, I'm working on a last minute graphics update - I know I asked around this on twitter as well, but will I be able to push that update to the server once I'm done? Or should I hold off on closing this until I've got that in.

**Comment by aarongustafson** [comment]
You will get an update link once it publishes. If you haven’t gotten the email/link yet when you have the tweak done, you can ping me on this thread and I will force it to update.

Should I hold off on screenshots until that}s done?

**Comment by webrender** [comment]
ok, I've added the /dist folder to the repo so all you should have to do is an `npm install` for the package.json dependencies and then `node server.js` will run it. 

yeah, much appreciated to hold off on a screenshot until that is done though :) i'll update this thread and ping you when i've got the graphics update posted.

**Comment by webrender** [comment]
oh, another question if you come back in here - does the server gzip SVGs?

**Comment by webrender** [comment]
Heya @aarongustafson, sorry for the late ping, I just finished putting up the graphics overhaul (and I'm very happy with it, payload clocks in gzipped @ 9.9kb :) ).  I never got an email regarding my entry though, where do I go from here?

**Comment by webrender** [comment]
btw there's an existing screenshot at http://webrender.net/10ktower.png if you'd like to use that.

**Comment by aarongustafson** [comment]
It should Gzip all text file types for sure.

**Comment by aarongustafson** [comment]
https://10ktower-10kapart2016.azurewebsites.net/

Yay

**Comment by webrender** [comment]
YAY!!! Thank you @aarongustafson!
