### ISSUE TITLE
Does this look right?

### ISSUE THREAD

**Issue by aarongustafson** [webrender/10ktower#3]
https://10ktower-10kapart2016.azurewebsites.net/

**Comment by webrender** [comment]
Haha, not quite! It looks like that is just displaying my SVG file (i.svg), not the actual application.  Perhaps this line in the web.config is incorrect? 

```
<rule name="StaticContent">
          <action type="Rewrite" url="dist/i.svg"/>
</rule>
```

**Comment by webrender** [comment]
the intent is that http://{{domain}}/i.svg should link to the static file, but all other URL requests should be sent through node.

**Comment by webrender** [comment]
@aarongustafson I've gone ahead and retested commit 5c637ec88dd2f70cf455e179d77d50c68c1f5a6c - you'll need to create a directory called 'towers' in the project root folder for the JSON save files. 

Once you do this, as long as you run an `npm install` and the port environment variable is set, `node server.js` should run the site correctly. Apologies for the trouble in setting up.

**Comment by aarongustafson** [comment]
Can you add the folder creation in Node? I have about 160 sites to deploy today :-)

**Comment by aarongustafson** [comment]
Maybe heck to see if it exists and if not, create it when you are trying to write to it?

**Comment by webrender** [comment]
@aarongustafson okie doke - I've added a couple lines to my server.js to check for the /towers directory and create it if it doesn't exist.

In addition I read up on the azure config rules a bit, and adjusted my web.config file - I think this time it will work properly :)

**Comment by aarongustafson** [comment]
Hmm… https://10ktower-10kapart2016.azurewebsites.net/

**Comment by webrender** [comment]
@aarongustafson ok, try one more time - i removed the static files section of the web.config altogether, as node will serve those properly anyways.  

Also, thank you for being so patient with this!

**Comment by webrender** [comment]
Closing this as the site now appears to be working properly.  Thank you again, I had such a good time working on this project!
